

export const GENRES: string[] = [
  'None',
  ...[
    'Acid House',
    'Acid Jazz',
    'Afro-Cuban Jazz',
    'Afrobeats',
    'Alternative Dance',
    'Alternative Rock',
    'Ambient',
    'Ambient Techno',
    'Americana',
    'Art Pop',
    'Art Rock',
    'Avant-Garde',
    'Baroque',
    'Bebop',
    'Big Band',
    'Black Metal',
    'Bluegrass',
    'Bluegrass Revival',
    'Blues',
    'Bollywood',
    'Boogie-Woogie',
    'Bossa Nova',
    'Breakbeat',
    'Bubblegum Pop',
    'Cajun',
    'Canterbury Scene',
    'Celtic',
    'Chamber Pop',
    'Chicago Blues',
    'Chillstep',
    'Chillwave',
    'Chiptune',
    'Christian Rock',
    'City Pop',
    'Classic Rock',
    'Classical',
    'Coldwave',
    'Comedy Rock',
    'Country',
    'Country Blues',
    'Cowpunk',
    'Crunk',
    'Crust Punk',
    'Dance',
    'Darkwave',
    'Death Metal',
    'Deep House',
    'Delta Blues',
    'Detroit Techno',
    'Disco',
    'Doo-wop',
    'Downtempo',
    'Dream Pop',
    'Drone',
    'Drum and Bass',
    'Dub',
    'Dubstep',
    'EDM',
    'Electric Blues',
    'Electro',
    'Electro Swing',
    'Electroclash',
    'Electronic',
    'Emo',
    'Eurodance',
    'Experimental',
    'Fado',
    'Flamenco',
    'Folk',
    'Folk Metal',
    'Folk Punk',
    'Freestyle',
    'Funk',
    'Future Bass',
    'Future Funk',
    'Gabber',
    'Game Boy Music',
    'G-Funk',
    'Garage Rock',
    'Glam Rock',
    'Glitch',
    'Gospel',
    'Gothic Rock',
    'Gqom',
    'Grime',
    'Grunge',
    'Hard Bop',
    'Hard Trance',
    'Hardcore Punk',
    'Hardstyle',
    'Heavy Metal',
    'Hip-Hop',
    'Honky Tonk',
    'House',
    'Hyperpop',
    'IDM',
    'Indie',
    'Indie Folk',
    'Indie Pop',
    'Indietronica',
    'Industrial',
    'J-Pop',
    'J-Rock',
    'JRPG BGM',
    'Jazz',
    'Jazz Fusion',
    'Jazz Rap',
    'Jersey Club',
    'Jungle',
    'K-Pop',
    'Kawaii Future Bass',
    'Krautrock',
    'Latin',
    'Liquid Funk',
    'Lo-fi',
    'Lo-fi Hip Hop',
    'Lounge',
    'Madchester',
    'Math Rock',
    'Meme Rap',
    'Merengue',
    'Metal',
    'Microhouse',
    'Minimal Techno',
    'Motown',
    'Neoclassical',
    'New Age',
    'New Wave',
    'No Wave',
    'Noise',
    'Noise Rock',
    'Northern Soul',
    'Nu Jazz',
    'Nu Metal',
    'Opera',
    'Phonk',
    'Pop',
    'Pop Punk',
    'Post-Punk',
    'Post-Rock',
    'Power Metal',
    'Progressive House',
    'Progressive Metal',
    'Progressive Rock',
    'Psychedelia',
    'Psychedelic Rock',
    'Psytrance',
    'Punk Rock',
    'R&B',
    'Raga',
    'Raga Rock',
    'Ragtime',
    'Reggae',
    'Reggaeton',
    'Rock',
    'Rock and Roll',
    'Rockabilly',
    'Salsa',
    'Samba',
    'Screamo',
    'Sea Shanty',
    'Shoegaze',
    'Singer-Songwriter',
    'Ska',
    'Ska Punk',
    'Skiffle',
    'Slacker Rock',
    'Sludge Metal',
    'Smooth Jazz',
    'Sophisti-pop',
    'Soul',
    'Southern Rock',
    'Soundtrack',
    'Space Rock',
    'Speed Metal',
    'Speedcore',
    'Spoken Word',
    'Stoner Metal',
    'Stoner Rock',
    'Surf Rock',
    'Swamp Rock',
    'Swing',
    'Synth-Pop',
    'Synthwave',
    'Tango',
    'Tech House',
    'Techno',
    'Thrash Metal',
    'Trance',
    'Trap',
    'Twee Pop',
    'UK Garage',
    'Vaporwave',
    'Video Game BGM',
    'Viking Metal',
    'Witch House',
    'World Music',
    'Zeuhl',
    'Zydeco',
  ].sort()
];

export const MOODS: string[] = [
  'None',
  ...[
    'Absurd',
    'Adventurous',
    'Aggressive',
    'Alien',
    'Ambitious',
    'Angelic',
    'Anxious',
    'Bittersweet',
    'Blissful',
    'Bold',
    'Bouncy',
    'Brave',
    'Breezy',
    'Brooding',
    'Bubbly',
    'Calm',
    'Cathartic',
    'Celebratory',
    'Chaotic',
    'Charming',
    'Cheeky',
    'Chic',
    'Childlike',
    'Chill',
    'Cinematic',
    'Classy',
    'Cold',
    'Comedic',
    'Comforting',
    'Confident',
    'Confused',
    'Content',
    'Courageous',
    'Cozy',
    'Crazy',
    'Creative',
    'Creepy',
    'Crisp',
    'Cruel',
    'Cute',
    'Cyberpunk',
    'Dainty',
    'Daring',
    'Dark',
    'Dashing',
    'Dazzling',
    'Deep',
    'Defiant',
    'Delicate',
    'Delightful',
    'Desperate',
    'Determined',
    'Devotional',
    'Dirty',
    'Dizzy',
    'Dramatic',
    'Dreamy',
    'Earthy',
    'Ecstatic',
    'Edgy',
    'Electric',
    'Elegant',
    'Emotional',
    'Empowering',
    'Enchanting',
    'Energetic',
    'Enigmatic',
    'Enthusiastic',
    'Epic',
    'Ethereal',
    'Euphoric',
    'Existential',
    'Exotic',
    'Exuberant',
    'Fantastical',
    'Festive',
    'Fierce',
    'Fiery',
    'Flirty',
    'Flowing',
    'Fluffy',
    'Free',
    'Frantic',
    'Fresh',
    'Friendly',
    'Frosty',
    'Frustrated',
    'Funky',
    'Futuristic',
    'Gentle',
    'Giddy',
    'Glamorous',
    'Gleeful',
    'Gloomy',
    'Glorious',
    'Goofy',
    'Graceful',
    'Grand',
    'Grateful',
    'Greasy',
    'Gritty',
    'Groggy',
    'Groovy',
    'Grumpy',
    'Gutsy',
    'Happy',
    'Harmonious',
    'Haunting',
    'Heady',
    'Heartbreak',
    'Heavenly',
    'Heavy',
    'Heroic',
    'Hilarious',
    'Hip',
    'Holy',
    'Hopeful',
    'Hot',
    'Humble',
    'Humorous',
    'Hyper',
    'Hypnotic',
    'Icy',
    'Idealistic',
    'Idyllic',
    'Imaginative',
    'Impulsive',
    'Industrial',
    'Innocent',
    'Inspiring',
    'Intense',
    'Intimate',
    'Introspective',
    'Ironic',
    'Irreverent',
    'Jaded',
    'Jazzy',
    'Jolly',
    'Joyful',
    'Jumpy',
    'Kitsch',
    'Laid-back',
    'Lazy',
    'Lethargic',
    'Lighthearted',
    'Lively',
    'Lonely',
    'Lush',
    'Lustful',
    'Lyrical',
    'Magical',
    'Majestic',
    'Meditative',
    'Melancholic',
    'Mellow',
    'Mighty',
    'Minimal',
    'Mischievous',
    'Misty',
    'Moody',
    'Morbid',
    'Motivational',
    'Mournful',
    'Mysterious',
    'Mystical',
    'Naughty',
    'Nervous',
    'Noble',
    'Noisy',
    'Nostalgic',
    'Obsessive',
    'Ominous',
    'Optimistic',
    'Opulent',
    'Outgoing',
    'Outrageous',
    'Overwhelmed',
    'Paranoid',
    'Passionate',
    'Patriotic',
    'Peaceful',
    'Pensive',
    'Perky',
    'Persuasive',
    'Pessimistic',
    'Petty',
    'Philosophical',
    'Pious',
    'Pizzicato',
    'Playful',
    'Poignant',
    'Pompous',
    'Positive',
    'Powerful',
    'Precious',
    'Pretty',
    'Primal',
    'Primeval',
    'Primordial',
    'Pristine',
    'Profound',
    'Proud',
    'Psychedelic',
    'Pulsating',
    'Pumping',
    'Punchy',
    'Pure',
    'Quiet',
    'Quirky',
    'Radiant',
    'Rainy',
    'Rambunctious',
    'Raw',
    'Rebellious',
    'Reckless',
    'Reflective',
    'Regretful',
    'Relaxed',
    'Relaxing',
    'Resigned',
    'Resolute',
    'Restless',
    'Retro',
    'Reverent',
    'Revolutionary',
    'Rhythmic',
    'Rich',
    'Risky',
    'Ritualistic',
    'Robotic',
    'Romantic',
    'Rough',
    'Rowdy',
    'Sacred',
    'Sad',
    'Salty',
    'Sarcastic',
    'Sassy',
    'Saturated',
    'Satirical',
    'Saucy',
    'Savage',
    'Scandalous',
    'Scary',
    'Schmaltzy',
    'Sensual',
    'Sentimental',
    'Serene',
    'Sexy',
    'Shy',
    'Silly',
    'Sinister',
    'Sleazy',
    'Slick',
    'Smooth',
    'Smoky',
    'Snarky',
    'Sneaky',
    'Soaring',
    'Solemn',
    'Solid',
    'Somber',
    'Sophisticated',
    'Soothing',
    'Soulful',
    'Spacious',
    'Sparkling',
    'Speedy',
    'Spicy',
    'Spirited',
    'Spiritual',
    'Spooky',
    'Sprightly',
    'Static',
    'Stately',
    'Steamy',
    'Stoic',
    'Stomping',
    'Stormy',
    'Strange',
    'Stressed',
    'Strong',
    'Stylish',
    'Suave',
    'Sublime',
    'Sunny',
    'Surreal',
    'Suspenseful',
    'Swanky',
    'Sweet',
    'Swirling',
    'Symphonic',
    'Syncopated',
    'Talkative',
    'Tender',
    'Tense',
    'Terrifying',
    'Thoughtful',
    'Threatening',
    'Timeless',
    'Touching',
    'Tranquil',
    'Trashy',
    'Triumphant',
    'Trippy',
    'Tropical',
    'Turbulent',
    'Twisted',
    'Unassuming',
    'Uncaring',
    'Unconventional',
    'Understated',
    'Uneasy',
    'Uninhibited',
    'Unpredictable',
    'Unreal',
    'Unsettling',
    'Uplifting',
    'Urban',
    'Urgent',
    'Valiant',
    'Velvety',
    'Vengeful',
    'Vibrant',
    'Vicious',
    'Victorious',
    'Vigorous',
    'Villainous',
    'Vintage',
    'Volatile',
    'Vulnerable',
    'Wacky',
    'Wandering',
    'Warm',
    'Weird',
    'Weightless',
    'Whimsical',
    'Wild',
    'Wired',
    'Wistful',
    'Witty',
    'Wonder',
    'Worldly',
    'Worried',
    'Wounded',
    'Yearning',
    'Youthful',
    'Zany',
    'Zealous',
  ].sort()
];

export const LYRICAL_STYLES: string[] = [
  'None',
  'Storytelling',
  'Abstract & Poetic',
  'Simple & Direct',
  'Conversational',
];

export const COUNTRY_VIBES: string[] = [
  'None',
  ...[
    'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
    'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
    'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
    'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic',
    'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia',
    'Fiji', 'Finland', 'France',
    'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
    'Haiti', 'Honduras', 'Hungary',
    'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Ivory Coast',
    'Jamaica', 'Japan', 'Jordan',
    'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
    'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
    'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
    'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway',
    'Oman',
    'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
    'Qatar',
    'Romania', 'Russia', 'Rwanda',
    'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria',
    'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu',
    'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
    'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam',
    'Yemen',
    'Zambia', 'Zimbabwe'
  ].sort()
];

export const LANGUAGES: string[] = [
  'No Language',
  'English',
  'Japanese',
  'Spanish',
  'French',
  'German',
  'Korean',
  'Italian',
  'Portuguese',
];

export const SONG_STRUCTURES = [
    { name: 'Select a template...', template: '' },
    { name: 'Verse-Chorus-Verse-Chorus', template: '[Verse 1]\n\n[Chorus]\n\n[Verse 2]\n\n[Chorus]' },
    { name: 'Verse-Chorus-Bridge-Chorus', template: '[Verse 1]\n\n[Chorus]\n\n[Verse 2]\n\n[Chorus]\n\n[Bridge]\n\n[Chorus]' },
    { name: 'AABA', template: '[Part A]\n\n[Part A]\n\n[Part B (Bridge)]\n\n[Part A]' },
    { name: 'Anime Opening (TV Size)', template: '[Intro]\n\n[Verse 1]\n\n[Pre-Chorus]\n\n[Chorus]\n\n[Outro]' },
    { name: 'Anime Opening (Full Size)', template: '[Intro]\n\n[Verse 1]\n\n[Pre-Chorus]\n\n[Chorus]\n\n[Verse 2]\n\n[Pre-Chorus]\n\n[Chorus]\n\n[Bridge]\n\n[Guitar Solo]\n\n[Chorus]\n\n[Outro]' },
    { name: 'Anime Ending (TV Size)', template: '[Verse]\n\n[Chorus]\n\n[Bridge]\n\n[Outro]' },
    { name: 'Anime Ending (Full Size)', template: '[Intro]\n\n[Verse 1]\n\n[Chorus]\n\n[Verse 2]\n\n[Chorus]\n\n[Bridge]\n\n[Chorus]\n\n[Outro]' },
    { name: 'J-Pop / J-Rock Structure', template: '[Intro]\n\n[Verse A]\n\n[Verse B / Pre-Chorus]\n\n[Chorus]\n\n[Interlude / Guitar Solo]\n\n[Bridge]\n\n[Chorus]\n\n[Outro]' },
    { name: 'Custom Full Song', template: '[Intro]\n\n[Verse 1]\n\n[Pre-Chorus]\n\n[Chorus]\n\n[Verse 2]\n\n[Pre-Chorus]\n\n[Chorus]\n\n[Bridge]\n\n[Chorus]\n\n[Outro]' }
];

export const STYLE_TEMPLATES = [
  {
    name: '80s Power Ballad',
    tags: ['80s rock ballad', 'powerful male vocals', 'emotional piano melody', 'epic guitar solo', 'gated reverb on drums', 'lush synthesizers', 'slow tempo', 'dynamic builds', 'anthem chorus']
  },
  {
    name: '90s Boom Bap',
    tags: ['boom bap hip hop', '90s east coast rap', 'jazzy samples', 'hard-hitting MPC drums', 'vinyl crackle', 'upright bass line', 'lyrical wordplay', 'raw and gritty production', 'DJ scratches', 'instrumental']
  },
  {
    name: 'Acoustic Folk',
    tags: ['singer-songwriter', 'acoustic folk', 'intimate male vocals', 'fingerpicked acoustic guitar', 'gentle harmonica', 'warm and organic production', 'heartfelt storytelling']
  },
  {
    name: 'Chill Video Game Vibe',
    tags: ['cozy video game music', 'animal crossing inspired', 'ukulele melody', 'light percussion', 'plucked synth bass', 'playful and quirky', 'relaxing tempo', 'whimsical sound effects', 'calm and happy mood', 'instrumental']
  },
  {
    name: 'Class Trial Frenzy',
    tags: ['high-speed acid jazz', 'psycho-pop', 'uptempo electronic beat', 'frantic piano melody', 'funky slap bass', 'energetic saxophone licks', 'video game OST', 'sense of urgency and chaos', 'detective mystery vibe']
  },
  {
    name: 'Cyberpunk Noir',
    tags: ['dark synthwave', 'dystopian ambient', 'Vangelis-inspired pads', 'heavy reverb', 'slow tempo', 'brooding saxophone melody', 'cinematic soundscape', 'rain and neon city sounds']
  },
  {
    name: 'Epic Movie Trailer Score',
    tags: ['cinematic orchestral music', 'epic score', 'hybrid orchestra', 'dramatic choir', 'braaam sound effects', 'huge percussion hits', 'building tension', 'triumphant theme', 'sound design elements', 'instrumental']
  },
  {
    name: 'Ghibli-esque Fantasy',
    tags: ['orchestral', 'Joe Hisaishi-inspired', 'emotional piano melody', 'lush string arrangements', 'whimsical woodwinds', 'magical and nostalgic', 'cinematic score', 'instrumental']
  },
  {
    name: 'Gothic Symphonic Metal',
    tags: [
        'symphonic black metal', 
        'gothic extreme metal', 
        'late 1990s style', 
        'baroque horror theatrics', 
        'melodic tremolo riffs', 
        'blast beats', 
        'orchestral layering', 
        'shrieked male highs',
        'guttural lows',
        'ethereal female soprano interludes', 
        'dramatic vocal delivery', 
        'darkly romantic mood', 
        'Victorian-gothic atmosphere', 
        'pipe organ', 
        'harpsichord', 
        'string ensembles', 
        'dense reverb-rich production'
    ]
  },
  {
    name: 'JRPG Battle Theme',
    tags: ['JRPG battle music', '16-bit soundfont', 'chiptune elements', 'fast-paced orchestral rock', 'electric guitar riffs', 'upbeat and intense', 'memorable melody', 'SNES-style reverb', 'video game OST']
  },
  {
    name: 'Modern Dark Pop',
    tags: ['dark pop', 'minimalist production', 'breathy female vocals', 'heavy 808 sub bass', 'whispered ad-libs', 'introspective lyrics', 'syncopated hi-hats', 'ASMR textures', 'haunting harmonies', 'modern pop sheen']
  },
  {
    name: 'Modern Lo-fi Beat',
    tags: ['lo-fi hip hop', 'chillhop', 'jazzy chords', 'boom bap drum pattern', 'vinyl crackle', 'tape hiss', 'relaxed tempo', 'mellow rhodes piano', 'nostalgic mood', 'instrumental']
  },
  {
    name: 'Pirate Metal Anthem',
    tags: ['folk metal', 'power metal', 'sea shanty melody', 'accordion', 'fiddle', 'heavy distorted guitars', 'galloping drum beat', 'epic gang vocals', 'triumphant and adventurous']
  },
  {
    name: 'Synthwave Racer',
    tags: ['synthwave', 'retrowave', '80s aesthetic', 'driving beat', 'arpeggiated synth bass', 'neon grid visuals', 'fast tempo', 'sawtooth synth leads', 'vintage drum machine']
  },
  {
    name: 'Urban J-Pop Fusion',
    tags: ['acid jazz', 'J-pop fusion', 'funky bassline', 'smooth female vocals', 'jazzy electric piano', 'stylish lead guitar', 'city pop influence', 'upbeat and cool']
  },
].sort((a, b) => a.name.localeCompare(b.name));

export const STYLE_STUDIO_TAGS: Record<string, Record<string, string[]>> = {
    'Instruments': {
        'Keyboards & Synths': [
            '8-bit Synth', 'Accordion', 'Acid Bassline', 'Celeste', 'Choir Synthesizer', 'Chiptune Synth', 'Clavinet',
            'Electric Piano', 'Farfisa Organ', 'FM Synth Bass', 'Grand Piano', 'Hammond B3 Organ', 'Harpsichord', 'Keytar', 'Keyboard',
            'Mellotron', 'Modular Synth', 'Organ', 'Overdriven Organ', 'Piano', 'Pipe Organ', 'Pluck Synth', 'Reese Bass',
            'Rhodes Piano', 'Sawtooth Synth Lead', 'Square Wave Synth', 'Sub Bass', 'Supersaw', 'Synth Bell', 'Synth Pad', 'Synth Strings', 'Synthesizer',
            'Theremin', 'Upright Piano', 'Vocoder', 'Wavetable Synth', 'Wobble Bass', 'Wurlitzer'
        ].sort(),
        'Guitars & Bass': [
            '12-string Acoustic Guitar', '7-String Guitar', 'Acoustic Guitar', 'Baritone Guitar', 'Bass', 'Bass Guitar',
            'Clean Electric Guitar', 'Classical Guitar', 'Distorted Guitar', 'Dobro', 'Electric Guitar', 'Fretless Bass', 'Fuzz Bass', 'Lap Steel Guitar', 'Overdriven Guitar',
            'Pedal Steel Guitar', 'Slap Bass', 'Steel-string Acoustic Guitar', 'Symphonic Guitar', 'Upright Bass'
        ].sort(),
        'Strings': [
            'Cello', 'Contrabasses', 'Harp', 'Orchestral Strings', 'Pizzicato Strings', 'Solo Violin', 'String Ensemble', 'String Quartet', 'Strings', 'Viola', 'Violin'
        ].sort(),
        'Brass': [
            'Brass Section', 'Euphonium', 'French Horn', 'Horns', 'Muted Trumpet', 'Saxophone Section', 'Trombone', 'Trumpet', 'Tuba'
        ].sort(),
        'Woodwinds': [
            'Bagpipes', 'Bass Clarinet', 'Bassoon', 'Clarinet', 'Contrabassoon', 'Duduk', 'English Horn', 'Flute', 'Harmonica',
            'Oboe', 'Pan Flute', 'Piccolo', 'Recorder', 'Saxophone', 'Shakuhachi'
        ].sort(),
        'Percussion': [
            '8-bit Drums', '808 Drum Machine', '808 Kick', '808 Snare', '909 Drum Machine', '909 Hi-hat', '909 Snare', 'Bongos', 'Cajon', 'Chimes', 'Clap',
            'Classic Percussion', 'Congas', 'Cowbell', 'Djembe', 'Drums', 'Glockenspiel', 'Gong', 'Handpan', 'Hi-hats', 'Kalimba',
            'Kick Drum', 'Latin Percussion', 'Marimba', 'Percussion', 'Retro Drum Machine', 'Tabla', 'Taiko Drums',
            'Tambourine', 'Timbales', 'Timpani', 'Triangle', 'Tubular Bells', 'Vibraphone', 'Xylophone'
        ].sort(),
        'Folk & World': [
            'Balalaika', 'Banjo', 'Bouzouki', 'Charango', 'Didgeridoo', 'Duduk', 'Erhu', 'Koto', 'Mandolin', 'Oud', 'Shamisen', 'Sitar',
            'Tin Whistle', 'Ukulele', 'Zither'
        ].sort(),
        'Electronic & DJ': [
            'DJ Mixer', 'Drum Machine', 'FX Samples', 'Groovebox', 'Sampler', 'TB-303', 'TR-808', 'TR-909', 'Turntables', 'Vocal Samples'
        ].sort()
    },
    'Production': {
        'Rhythm & Tempo': [
            'Adagio', 'Allegro', 'Blast Beat', 'Double-time Feel', 'Driving Rhythm', 'Four-on-the-floor', 'Half-time Feel',
            'Intense Boss Battle Rhythm', 'Intricate Drum Fills', 'Polyrhythmic', 'Slow Tempo', 'Swing Rhythm', 'Syncopation', 'Upbeat Tempo'
        ].sort(),
        'Mixing & Effects': [
            '80s Gated Reverb', 'Atmospheric', 'Big Room Reverb', 'Bitcrushing', 'Chorus Effect', 'Crisp Mix', 'Delay (Ping-Pong)',
            'Ethereal Pads', 'Filter Sweep', 'Flanger', 'Gritty Distortion', 'Heavy Reverb', 'Lo-fi Filtering',
            'Panning Automation', 'Parallel Compression', 'Phaser', 'Plate Reverb', 'Sidechain Compression', 'Spring Reverb',
            'Stereo Widening', 'Tape Delay', 'Vintage Tape Saturation'
        ].sort(),
        'Harmony & Melody': [
            'Arpeggiated', 'Catchy Melodies', 'Counter-melody', 'Dissonant Chords', 'Glissando', 'Lush Harmonies',
            'Melodic Bassline', 'Modal Interchange', 'Ostinato', 'Slick Bassline', 'Soaring Anime Vocals', 'Vibrato'
        ].sort(),
        'Arrangement & Dynamics': [
            'Buildup', 'Crescendo', 'Decrescendo', 'Drop', 'Dynamic Builds', 'Epic Orchestral Mix', 'Forte', 'Intricate Arrangements',
            'Layered Textures', 'Minimalist Repetition', 'Orchestral Stabs', 'Piano (dynamic)', 'Riser', 'Sforzando',
            'Sparse Arrangement'
        ].sort(),
        'Genre & Vibe': [
            'Ambient Wash', 'Breakdown', 'City Pop Groove', 'Funky Bassline', 'J-Rock Energy', 'Kawaii Future Bass', 'Lo-fi Aesthetic',
            'Modern Pop Sheen', 'Motown Groove', 'Shibuya-kei Influence', 'Technical Guitar Riff', 'Twangy Guitar',
            'Wall of Sound', 'Warm Analog Synths'
        ].sort(),
        'Retro & Chiptune': [
            '8-bit Sound Design', 'Bitcrushed Drums', 'Catchy 8-bit Melody', 'Chiptune Harmonies',
            'Earthbound-inspired Sample Chops', 'Fast Arpeggios', 'Noise Channel Percussion', 'Pulse Width Modulation (PWM)',
            'Quirky Sound Effects (SFX)', 'SNES-style Reverb', 'Triangle Wave Bass', 'Video Game OST Feel'
        ].sort()
    },
    'Vocals': {
      'Vocal Style': [
        'Aggressive Vocals', 'Angelic Choir', 'ASMR', 'Breathy Vocals', 'Child Vocals', 'Death Metal Growl', 'Deep Male Voice', 'Falsetto', 'Female Vocals', 'Gospel Choir', 'Guttural Vocals', 'High-Pitched Vocals', 'Male Vocals', 'Melismatic Singing', 'Operatic Vocals', 'Rap Vocals', 'Raspy Voice', 'Robotic Vocals', 'Screaming', 'Shouting', 'Singing', 'Soulful Vocals', 'Spoken Word', 'Whispering', 'Yodeling'
      ].sort(),
      'Vocal Effects': [
        'Auto-Tune', 'Chorus Effect', 'Distorted Vocals', 'Echo', 'Harmonies', 'Layered Vocals', 'Muffled Vocals', 'Reverb', 'Vocal Chops', 'Vocoder'
      ].sort(),
    },
    'Era & Influence': {
      'Decades': [
        '1920s', '1930s', '1940s', '1950s', '1960s', '1970s', '1980s', '1990s', '2000s', '2010s', '2020s'
      ].sort(),
      'Historical Periods': [
        'Baroque', 'Classical Era', 'Medieval', 'Renaissance', 'Romantic Period'
      ].sort(),
      'Cultural Influence': [
        'African Rhythms', 'Anime OST', 'Bollywood Music', 'Brazilian Samba', 'Celtic Folk', 'City Pop Influence', 'Ghibli-esque', 'JRPG Soundtrack', 'K-Pop Sound', 'Latin Percussion', 'Motown Sound', 'Shibuya-kei', 'Vangelis-inspired'
      ].sort(),
    },
    'Recording & Fidelity': {
      'Fidelity': [
        '4-track Cassette Sound', '8-bit', '12-bit', '16-bit', 'Analog Warmth', 'Clean Production', 'Demo Quality', 'DIY Aesthetic', 'High-Fidelity', 'Lo-fi', 'Noisy', 'Polished Production', 'Raw Recording', 'Studio Quality'
      ].sort(),
      'Ambiance & Space': [
        'Arena Reverb', 'Auditorium Ambience', 'Cathedral Reverb', 'Chamber Reverb', 'Club Atmosphere', 'Concert Hall Sound', 'Intimate Recording', 'Large Hall Recording', 'Outdoor Ambience', 'Room Noise', 'Stadium Sound', 'Underwater Effect'
      ].sort(),
      'Hardware & Medium': [
        'Cassette Tape Hiss', 'Fairlight CMI sounds', 'LinnDrum Machine', 'MPC Drums', 'Roland TR-808', 'Roland TR-909', 'Talkbox', 'Vinyl Crackle', 'Vintage Microphone Sound'
      ].sort(),
    },
    'Sound Effects': {
      'Nature & Weather': ['Animal Sounds', 'Birds Chirping', 'Ocean Waves', 'Rain Sounds', 'Thunder', 'Wind Howling'].sort(),
      'Urban & Mechanical': ['Alarm Clock', 'Car Horns', 'City Ambience', 'Explosion', 'Police Siren', 'Static', 'Train Sounds', 'Typing Sounds'].sort(),
      'Abstract & Sci-Fi': ['Alien Sounds', 'Computer Noises', 'Glitch Sounds', 'Laser Zaps', 'Riser', 'Sci-Fi Soundscape', 'Swoosh', 'Teleport Sound'].sort(),
    },
    'VSTs & Software': {
        'Synthesizers': [
            '3xOsc', 'Arp Sequence', 'Arturia Pigments', 'Diva', 'FM Synthesis Pad', 'Magical 8bit Plug', 'Massive', 'Massive X',
            'Moog Subsequent', 'Native Instruments FM8', 'NES Synth', 'Nexus 4', 'Omnisphere', 'Phase Plant', 'SID Chip Emulation', 'Spire',
            'Supersaw Lead', 'Sylenth1', 'TAL-U-NO-LX', 'U-He Zebra2', 'Vital Audio Vital', 'Vocaloid Synth', 'Xfer Serum',
            'Yamaha DX7-style FM Pad'
        ].sort(),
        'Bass': [
            '808 Sub Bass', 'SubLab', 'Trilian', 'Wobbly Bass'
        ].sort(),
        'Sample Libraries': [
            'Arturia Piano', 'Cinesamples CineStrings', 'EastWest Hollywood Strings', 'Heavyocity Gravity', 'Keyscape', 'Kontakt',
            'Kontakt Noire Piano', 'Output Arcade', 'ProjectSAM Symphobia', 'Shreddage X', 'Spitfire Albion One', 'Spitfire Audio LABS Soft Piano'
        ].sort(),
        'Samples & Soundfonts': [
          'Amen Break', 'Classic JRPG Soundfont', 'GBA-style Soundfont', 'Japanese Indie Game Soundfont', 'LinnDrum Samples',
          'MPC Swing', 'Orchestral Hit Stab', 'Retro Game Samples', 'SGM Soundfont', 'SNES Soundfont'
        ].sort(),
        'Effects & Processing': [
            'Bitcrushed', 'CamelCrusher', 'FabFilter Pro-Q 3', 'Glitch Effects', 'Granular Texture', 'iZotope Ozone',
            'OTT Compression', 'Professional Mastering', 'RC-20 Retro Color', 'Risers/Sweeps', 'SoX Resampler',
            'Soundtoys Decapitator', 'Trance Gate', 'Valhalla Supermassive', 'Warped Vocal Sample', 'Xfer LFO Tool'
        ].sort()
    }
};

export const MOOD_COLORS: Record<string, { from: string; via: string; to: string }> = {
  'None': { from: '#111827', via: 'rgba(76, 29, 149, 0.4)', to: '#111827' },
  'Happy': { from: '#f59e0b', via: 'rgba(234, 179, 8, 0.3)', to: '#111827' },
  'Sad': { from: '#1e3a8a', via: 'rgba(55, 65, 81, 0.4)', to: '#111827' },
  'Melancholic': { from: '#312e81', via: 'rgba(88, 28, 135, 0.3)', to: '#111827' },
  'Energetic': { from: '#9f1239', via: 'rgba(236, 72, 153, 0.4)', to: '#111827' },
  'Aggressive': { from: '#991b1b', via: 'rgba(239, 68, 68, 0.4)', to: '#111827' },
  'Chill': { from: '#0d9488', via: 'rgba(6, 182, 212, 0.3)', to: '#111827' },
  'Creepy': { from: '#171717', via: 'rgba(131, 24, 67, 0.4)', to: '#111827' },
  'Dark': { from: '#171717', via: 'rgba(23, 37, 84, 0.4)', to: '#111827' },
  'Dreamy': { from: '#86198f', via: 'rgba(217, 70, 239, 0.3)', to: '#111827' },
  'Epic': { from: '#581c87', via: 'rgba(212, 175, 55, 0.3)', to: '#111827' },
  'Emotional': { from: '#5b21b6', via: 'rgba(139, 92, 246, 0.3)', to: '#111827' },
  'Hopeful': { from: '#065f46', via: 'rgba(16, 185, 129, 0.3)', to: '#111827' },
  'Mysterious': { from: '#4a044e', via: 'rgba(17, 24, 39, 0.5)', to: '#111827' },
  'Romantic': { from: '#be185d', via: 'rgba(251, 146, 60, 0.3)', to: '#111827' },
  'Uplifting': { from: '#0ea5e9', via: 'rgba(250, 204, 21, 0.4)', to: '#111827' }
};
